import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Logo from "../../public/images/profile/MainLogo.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icon";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
export default function Home() {
  return (
    <>
      <Head>
        <title>Rihen</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect></TransitionEffect>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-2/5 md:w-full">
              <Image
                src={Logo}
                alt="Rihen Logo"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                property
                sizes="(max-width: 768px) 100vw, (max-width:120px) 50vw, 50vw"
              ></Image>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Creativity"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-4xl md:!text-3xl
                sm:!text-2xl sm:py-4"
              />
              <p className="my-4 text-lg font-medium md:text-base sm:text-sm">
                Rihen serves a wide variety of audiences, including creative
                studios, independent developers, technology and electronics
                companies, advertising agencies, and educational institutions,
                with a global vision of democratizing powerful solutions for
                each sector.
              </p>

              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/connection"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                >
                  Intranet <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="/mailto:mihir.roy266@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark
                   underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="buld" className="w-full h-auto"></Image>
        </div>
      </main>
    </>
  );
}
